package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.IncomeRecord;

import java.util.List;
import java.util.Map;

public interface IncomeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    int insert(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    int insertSelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    IncomeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    int updateByPrimaryKeySelective(IncomeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_income_record
     *
     * @mbggenerated Tue Jul 10 11:25:39 CST 2018
     */
    int updateByPrimaryKey(IncomeRecord record);

    /**
     * 根据用户标识分页查询收益记录
     * @param paramMap
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByPage(Map<String, Object> paramMap);

    /**
     * 查询用户的所有收益记录总数
     * @param paramMap
     * @return
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 根据收益状态及当前系统时间查询收益记录
     * @param IncomeStatus
     * @return
     */
    List<IncomeRecord> selectIncomeRecordByIncomeStatusAndIncomeDate(Integer IncomeStatus);
}